version: 0.1.2.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore .\development\Beyova.ProjectItemConditionExtension.sln
build:
  project: development/Beyova.ProjectItemConditionExtension.sln
  verbosity: normal
artifacts:
- path: .\development\Beyova.ProjectItemConditionExtension\bin\Release\Beyova.ProjectItemConditionExtension.vsix
deploy:
- provider: GitHub
  tag: release-v$(appveyor_build_version)
  draft: true
  on:
    branch: master